parameters:
  countries:
    commonRegexPrefix: '^'
    commonRegexSuffix: '$'
    replacements:
      "argentina":                                     "AR"
      "australia":                                     "AU"
      "belgium":                                       "BE"
      "canada":                                        "CA"
      "chile":                                         "CL"
      "costa rica":                                    "CR"
      "croatia":                                       "HR"
      "czech( republic)?":                             "CZ"
      "d[ea]nmark":                                    "DK"
      "(germany|Deutschland)":                         "DE"
      "finland":                                       "FI"
      "france":                                        "FR"
      "(uk|england|united kingdom)":                   "GB"
      "hungary":                                       "HU"
      "ireland":                                       "IE"
      "(italia|italy)":                                "IT"
      "mexico":                                        "MX"
      "(the )?netherlands":                            "NL"
      "new zealand":                                   "NZ"
      "norway":                                        "NO"
      "russia":                                        "RU"
      "poland":                                        "PL"
      "portugal":                                      "PT"
      "slovakia":                                      "SK"
      "sweden":                                        "SE"
      "switzerland":                                   "CH"
      "ukraine":                                       "UA"
      "united states( of america)?":                   "US"
      "(u\\.?s\\.?( of america)?|usa)":                "US"
      "south africa":                                  "ZA"

  states:
    commonRegexPrefix: '^'
    commonRegexSuffix: '$'
    replacements:
      'AK$|^Alaska':                    'Alaska'
      'AL$|^Alabama':                   'Alabama'
      'AR$|^Arkansas':                  'Arkansas'
      'AZ$|^Arizona':                   'Arizona'
      'CA$|^California':                'California'
      'CO$|^Colorado':                  'Colorado'
      'CT$|^Connecticut':               'Connecticut'
      'DE$|^Delaware':                  'Delaware'
      'FL$|^Florida':                   'Florida'
      'GA$|^Georgia':                   'Georgia'
      'HI$|^Hawaii':                    'Hawaii'
      'IA$|^Iowa':                      'Iowa'
      'ID$|^Idaho':                     'Idaho'
      'IL$|^Illinois':                  'Illinois'
      'IN$|^Indiana':                   'Indiana'
      'KS$|^Kansas':                    'Kansas'
      'KY$|^Kentucky':                  'Kentucky'
      'LA$|^Louisiana':                 'Louisiana'
      'MA$|^Massachusetts':             'Massachusetts'
      'MD$|^Maryland':                  'Maryland'
      'ME$|^Maine':                     'Maine'
      'MI$|^Michigan':                  'Michigan'
      'MN$|^Minnesota':                 'Minnesota'
      'MO$|^Missouri':                  'Missouri'
      'MS$|^Mississippi':               'Mississippi'
      'MT$|^Montana':                   'Montana'
      'NC$|^North Carolina':            'North Carolina'
      'ND$|^North Dakota':              'North Dakota'
      'NE$|^Nebraska':                  'Nebraska'
      'NH$|^New Hampshire':             'New Hampshire'
      'NJ$|^New Jersey':                'New Jersey'
      'NM$|^New Mexico':                'New Mexico'
      'NV$|^Nevada':                    'Nevada'
      'NY$|^New York':                  'New York'
      'OH$|^Ohio':                      'Ohio'
      'OK$|^Oklahoma':                  'Oklahoma'
      'OR$|^Oregon':                    'Oregon'
      'PA$|^Pennsylvania':              'Pennsylvania'
      'RI$|^Rhode Island':              'Rhode Island'
      'SC$|^South Carolina':            'South Carolina'
      'SD$|^South Dakota':              'South Dakota'
      'TN$|^Tennessee':                 'Tennessee'
      'TX$|^Texas':                     'Texas'
      'UT$|^Utah':                      'Utah'
      'VA$|^Virginia':                  'Virginia'
      'VT$|^Vermont':                   'Vermont'
      'WA$|^Washington':                'Washington'
      'WI$|^Wisconsin':                 'Wisconsin'
      'WV$|^West Virginia':             'West Virginia'
      'WY$|^Wyoming':                   'Wyoming'

      'AB$|^Alberta':                   'Alberta'
      'BC$|^British Columbia':          'British Columbia'
      'MB$|^Manitoba':                  'Manitoba'
      'NB$|^New Brunswick':             'New Brunswick'
      'NL$|^Newfoundland and Labrador': 'Newfoundland and Labrador'
      'NS$|^Nova Scotia':               'Nova Scotia'
      'ON$|^Ontario':                   'Ontario'
      'PE$|^Prince Edward Island':      'Prince Edward Island'
      'QC$|^Qu[eé]bec':                 'Québec'
      'SK$|^Saskatchewan':              'Saskatchewan'
