# Will not make the following available in filters:
# - Any kind of "Closed species"/"Copyrighted characters"
#     will not make it easier for anyone to disrespect others' rights; "Closed species (with permission)" is OK

parameters:
  species_definitions:
    valid_choices:
      "Most species": # grep-assumed-does-specie-when-artisan-has-only-doesnt
        "Real life animals":
          Birds:
            Ducks:

          'i_Existing species': {}

          Fishes:
            Sharks:

          Mammals:
            "i_Most Mammals":
            Bears:
              Giant pandas:
            Canines:
              Lupines:
                Wolves:
              Vulpines:
                Foxes:
              Dogs:
                'Domestic dogs':
                  'Border collies': {}
                  'Welsh corgis': {}
              Coyotes: {}
              Jackals: {}
            Felines:
              "Big cats":
                Caracals:
                Lions:
                Lynxes:
                Tigers:
              "Small cats":
                "Domestic cats":
            Marsupials:
              Kangaroos:
              Opossums:
            Mustelids:
              Ferrets:
              Otters:
              Weasels: {}
            Primates:
              Apes:
              Monkeys:
            Rodents:
              Mice:
              Rats:
            Ungulates:
              "i_Ungulates (tests now)":
              Bovines:
                Antelopes: {}
                Cows:
              Cervines:
                Deers:
                  Caribous: {}
              Equines: # Avoid?
                Donkeys: {}
                Horses:
              Goats:
              Rhinos:
              Sheeps:
            Bats:
            Elephants:
            Hyenas:
            Pinnipeds:
            Rabbits:
            Raccoons:
            Red pandas:
            Sloths:

          Reptiles:
            Dinosaurs: # Introduce "Extinct" group?
            Lizards:
            "i_Most reptiles":
            "i_Reptiles (not including dragons)": {}

          Bugs:
            Arachnids:
              Spiders: {}
            'i_Caterpillars': {}
            Insects: {}

          Amphibians:

        "Fantasy creatures":
          'i_Avalis': {}
          'i_Demon cats': {}
          'i_Fantasy': {}
          "i_Fantasy / mythical creatures":
          'i_Mythical': {}
          Dragons:
            "Angel Dragons":
              "Dutch Angel Dragons": {}
            "i_*Extremely intricate dragons": {}
          Robotic/cybernetic/mechanical:
            Ampwaves:
            "i_Any mechanical/inorganic species":
            'i_Anything electronic': {}
            "i_Ask for mechanic/electronic creatures":
            'i_Cyborgs':
            "i_Full robospecies":
            'i_Mechanical species (protogens and the like)': {}
            Primagens:
            Protogens:
            "i_Robots":
            "i_Robotics":
            Synths:
            "i_Species with robotic/cybernetic, or otherwise mechanical appearance":
            'i_3D printing & electronics required species (e.g. Protogens, Skullies)':
          Crux:
          Drekkubuses:
          "Ghost Bones Dragon":
          Gryphons:
          Lloteer: # WAT
          Manokits:
          MLP:
          Monsters:
          Pancans:
          Pokemons:
          Sergals:
          'i_Skull-*':
            'i_Skull':
            'i_Skullsuits':
            'i_Skull Creatures':
            'i_Skulldogs':
            'i_Skull animals':
            'i_3D printing & electronics required species (e.g. Protogens, Skullies)':
          Sparkledogs:
          Wickerbeasts:

        Aquatic: # Fill
          "i_Creatures that live solely in water":
          "i_Dolphins":
          Fishes:
          "i_Most real-life aquatics that have a smooth head":
          Otters:
          "i_Sea creatures": # Aquatic?
          "i_Whales":

        Hooved: # Fill
          Ungulates: {}
          "i_Deer&similar":
          MLP: {}
          "i_Pony": # Does it mean lil horse or MLP?

        Hybrids:
          "i_All hybrids":
          "i_Complex hybrids":
          "i_Hybrids of these":
          "i_Mixed species":
          Pancans: {}

        Scalies: # Fill
          Dragons: {}
          "i_Most Scalies":
          Reptiles: {}
          "i_Some scalies":

        Winged: # Fill
          Birds: {}
          Dragons: {}
          Bats: {}
          Gryphons: {}
          Pancans: {}

        With antlers: # Fill
          Cervines: {}
          Goats: {}

        With beak:
          Birds: {}
          Pancans: {}

      Other: # grep-species-other
        "i_Copyright-related classification?": # FIXME
          "i_Copyrighted characters":
            'i_Copyrighted characters (e.g. Pokemons)':
          "i_Copyrighted species": # Alias of below?
          "i_Closed species":
          "i_Open species":
          "i_Self-made species":
          "i_Original species":
          "i_I won't do closed species without the permission from the maker itself (some artists don't want their species made into a fursuit!)":
          "i_Will not do a closed species without permission": # TODO: Should be equal to closed species; getfursu.it will not help steal designs
          "i_Your own specific species":
          "i_Own species":
          "i_Most of author's species":

        "i_Other/Unclassified": # Just to silence the validator, to be fixed/approved/categorized later
          "i_Fantasy/original species":
          "i_Any mythical or unique species":
          "i_Any animal and most mysticals (dragons*, serials, gryphons)":
          'i_Any design that does not use faux fur': {}
          "i_Rare species":

          "i_Dutch Angel Dragons (Tail, paws and feet paws ONLY)": # FIXME: Moving this under "DADs" causes the filter subcategory arrow-button to show up and do nothing, see also #89
          "i_Protogens (for paws and tail ONLY)": # FIXME: see above

          "i_Some video game characters":
          "i_Most any species": # ?!
          'i_Most common': {}

          "i_Anything cultural appropriation":
          "i_Anything requiring extensive electronics (ex: true-to-species protogens, though we could do a simplified \"toony\" version)":
          "i_Axolotls":
          "i_Basic canines, vulpines, angel dragons. (Will consider if unique)":
          "i_Cervidae/deer family species with large antlers":
          "i_Critters":
          "i_Etc.": # De hecc

          "i_Complexity-related":
            "i_Complex species, as if the species has too many parts and details, I will say so during the quote.":
            "i_Extremely intricate anything":
            "i_Heavily complicated creatures":

          "i_Fur-covered":
            "i_All species and all fur based characters":
            "i_Any species that is furry! (canines, felines, fur dragons, horses, rodents, bats, etc.)":
            'i_I am willing to do all types of furry species at the moment': {}
            "i_I'm happy to make most species as long as they're covered in fur":
            "i_Most anything covered in fur":

          "i_Furbies":
          "i_Gem raptors":
          "i_Humanoids":
            "i_Humans":
          "i_I can also do velvet or minky skinned characters":
          "i_I make exceptions on rare occasions":
          "i_Invertibrates":
          'i_I will not do anything representing satanism': {}
          "i_Most furless/featherless species":
          "i_No airbrushed / gradient markings on any species (all work is sewn)":
          "i_Only because I do not currently have the ability to do the electronic work on them": # This should have been a comment
          "i_Others": # Change to the parent category
          "i_Please inquire about fantasy creatures":

          "i_Raptor masks":

          'i_Saber-toothed tiger': {}
          "i_Specialises in mythical creatures/monsters":
          "i_Species with horizontal pupils":
          "i_Things of an adult nature":
          "i_Unsafe creations":

          "i_Uncommon species":
          "i_Will not work with sequin for characters":

    regex_prefix: '(?<=^|\n)'
    regex_suffix: '(?=\n|$)'
    replacements:
      '^(any|all|most)( species)?$':                         'Most species'

      "AD's|(Ange?le? dragons?)":                            'Angel Dragons'
      'Amphibians?':                                         'Amphibians'
      'Antelopes?':                                          'Antelopes'
      'Avians?':                                             'Birds'
      'Bats?':                                               'Bats'
      'Bears?':                                              'Bears'
      'Big/small felines':                                   "Big felines\nSmall felines"
      'Big and small cats':                                  "Big cats\nSmall cats"
      'Big (cats|felines)( in general)?':                    "Big cats"
      'Birds?':                                              'Birds'
      'Birds/avians in general':                             'Birds'
      'Bovines?':                                            'Bovines'
      'Bunn(y|ies)':                                         'Rabbits'
      'Caracles|Caracals?':                                  'Caracals'
      'Cats?( in general)?':                                 'Felines'
      'Canines?( in)? ?(\(?general\)?)?':                    'Canines'
      'Caribous?':                                           'Caribous'
      'Cervines?':                                           'Cervines'
      'copyrighted characters?[ !]*':                        'Copyrighted characters'
      '(any )?Closed? species?':                             'Closed species'
      'Coyotes?':                                            'Coyotes'
      'Cows?':                                               'Cows'
      'Deers?':                                              'Deers'
      'Dinosaurs?':                                          'Dinosaurs'
      'Dogs?':                                               'Dogs'
      'Domestic Cats?':                                      'Domestic cats'
      'Donkeys?':                                            'Donkeys'
      'Dragons?':                                            'Dragons'
      'Dre[ck]{2}ubus(es)?':                                 'Drekkubuses'
      'Dutch Angel Dragons/Angel Dragons':                   "Dutch Angel Dragons\nAngel Dragons"
      'Dutchies|DAD''s|Dutch ange?le? dragons?':             'Dutch Angel Dragons'
      'Equines?( in general)?':                              'Equines'
      'Etc\.?':                                              'Etc.'
      'Fantasie':                                            'Fantasy creatures'
      'Felines?( in general)?':                              'Felines'
      'Ferrets?':                                            'Ferrets'
      'Fish(es)?':                                           'Fishes'
      'Fox(es)?':                                            'Foxes'
      'Gem Raptors?':                                        'Gem raptors'
      'Goats?':                                              'Goats'
      'Griff[io]ns?|Gryphons?':                              'Gryphons'
      'Horses?':                                             'Horses'
      'Hybride?s?':                                          'Hybrids'
      'Hyenas?':                                             'Hyenas'
      'Humanoids?':                                          'Humanoids'
      'Humans?':                                             'Humans'
      'Jackals?':                                            'Jackals'
      'K-?9''?s':                                            'Canines'
      'Kangaroos?':                                          'Kangaroos'
      'Lions?':                                              'Lions'
      'Lynx(es)?':                                           'Lynxes'
      'Mammals?( in general)?':                              'Mammals'
      'Mann?okits?':                                         'Manokits'
      'Monkeys?( in general)?':                              'Monkeys'
      'Mouse':                                               'Mice'
      'Open species?':                                       'Open species'
      'Opossums?':                                           'Opossums'
      'Otters?':                                             'Otters'
      'Pandas?':                                             'Giant pandas'
      'Pinnipeds?( in general)?':                            'Pinnipeds'
      'Primagens and protogens':                             "Primagens\nProtogens"
      'Pokemons?':                                           'Pokemons'
      'Primagens?':                                          'Primagens'
      'Protogens?':                                          'Protogens'
      'Protogens?/primagens?':                               "Protogens\nPrimagens"
      'Rabbits?':                                            'Rabbits'
      'Racc?oo?ns?':                                         'Raccoons'
      'Rams?':                                               'Sheeps'
      'Rats?':                                               'Rats'
      'Rare/closed species':                                 "Rare species\nClosed species"
      'Red pandas?':                                         'Red pandas'
      'Reptiles?':                                           'Reptiles'
      'Reptilians?( in general)?':                           'Reptiles'
      'Robots?':                                             'Robots'
      'Rodents?( in general)?':                              'Rodents'
      'Sables':                                              'Sable antelope'
      '(any )?Scalies?( in general)?':                       'Scalies'
      'Ser[gi]als?':                                         'Sergals'
      'Sheeps?':                                             'Sheeps'
      'Skull Animals?':                                      'Skull animals'
      'Small felines?':                                      'Small cats'
      'Snow leopards?':                                      'Snow leopards'
      'Synths/protogens':                                    "Synths\nProtogens"
      'Weasels?':                                            'Weasels'
      'Wicker ?beas?ts?':                                    'Wickerbeasts'
      'Wolf':                                                'Wolves'
      'Ungulates?(( in)? \(?general\)?)?':                   'Ungulates'
      'Vulpines?':                                           'Vulpines'
