parameters:
  species_definitions:
    valid_choices:
      "Most species": # grep-assumed-does-specie-when-artisan-has-only-doesnt
        "Real life animals":
          Birds:
            Ducks:

          Fishes:
            Sharks:

          Mammals:
            Bears:
              Giant pandas:
            Canines:
              Lupines:
                Wolves:
              Vulpines:
                Foxes:
                  Fennecs:
              Dogs:
            Felines:
              "Big cats":
                Caracals:
                Lions:
                Lynxes:
                Snow leopards:
                Tigers:
              "Small cats":
                "Domestic cats":
            Mustelids:
              Ferrets:
              Otters:
            Rodents:
              Mice:
              Rats:
            Ungulates:
              Antelopes:
                Sable antelope:
              Bovines:
                Cows:
              Cervines:
                Deers:
              Equines: # Avoid?
                Horses:
              Goats:
              Rhinos:
              Sheeps:
            Bats:
            Elephants:
            Hyenas:
            Kangaroos:
            Monkeys:
            Opossums:
            Pinnipeds:
            Rabbits:
            Raccoons:
            Red pandas:

          Reptiles:
            Lizards:

          Amphibians:
          Insects:

        "Fantasy creatures":
          Robotic/cybernetic/mechanical:
            Primagens:
              "i_Primagens (on a foam base)":
            Protogens:
              "i_Protogens (on a foam base)":

          "Angel Dragons":
          Crux:
          Digimons:
          Dragons:
          Drekkubuses:
          Dutchies:
          "Dutch Angel Dragons":
          "Ghost Bones Dragon":
          Gryphons:
          Lloteer: # WAT
          Manokits:
          MLP:
          Monsters:
          Pancans:
          Pokemons:
          Sergals:
          "Skull animals":
          Sparkledogs:
          "TV heads":
          Wickerbeasts:

        "All hybrids":
          Hybrids:
            Pancans:
          "i_Hybrids of these":

        Aquatic: # Fill
          Fishes:
          Otters:

        Hooved: # Fill
          MLP:
          Ungulates:

        Scalies: # Fill
          Dinosaurs:
          Dragons:
          Reptiles:

        Winged: # Fill
          Birds:
          "Angel Dragons":
          Bats:
          Dragons:
          "Dutch Angel Dragons":
          Gryphons:
          Pancans:

        With antlers: # Fill
          Antelopes:
          Cervines:
          Goats:

        With beak:
          Birds:
          Pancans: # Add above

        "i_Copyright-related classification?": # FIXME
          "Copyrighted characters":
          "Copyrighted species": # Alias of below?
          "Closed species":
          "Open species":
          "Self-made species":
          "Original species":

      "i_To be fixed": # Just to silence the validator, to be fixed/approved later
        'Others':
        'Robots':
        'Most comfortable with Canines':
        'Heavily complicated creatures':
        'Gem raptors':
        'Most species - probably less likely to do unusual species like aquatics or unusually-shaped reptiles or reptiles':
        "Most experienced in wolves":
        "I'd prefer not to do any pokemon/digimon, but still ask since it depends on the design":
        "Some birds (unless its on another headbase then I'll do it)":
        "Raptor masks":
        "Protogens (for paws and tail ONLY)":
        "Dutch Angel Dragons (Tail, paws and feet paws ONLY)":
        "Any mythical or unique species":
        "I will do any but I prefer not to do canines":
        "I greatly prefer uncommon species and will be much more excited to work on such species. I do all, but uncommon is prefered.":
        "Etc.": # De hecc
        "Robotic stuff":
        'Almost anything organic (non robotic/cybernetic)':
        'Species with robotic/cybernetic, or otherwise mechanical appearance':
        "All species and all fur based characters":
        "Skullsuits":
        "Anyone since we like to experience new species":
        "Nothing on the hard pass list, but I do not have experience with scalies or other animals without fur. I am willing to try anything!":
        "Any species that is furry! (canines, felines, fur dragons, horses, rodents, bats, etc.)":
        "I can also do velvet or minky skinned characters":
        "*Extremely intricate dragons":
        "Extremely intricate anything":
        "None specifically that I can think of, if unsure just ask":
        'Any animal and most mysticals (dragons*, serials, gryphons)':
        'Any and all within my capabilities of foam/fur/minky crafting. Unique or uncommon species are my soft spot.':
        'A big fan of things with horns and claws':
        'Not sure yet':
        'Unsafe creations':
        'I like to make unusual creatures and monsters':
        'Things of an adult nature':
        'Standard animals are fine as well':
        "I enjoy making monsters and creepy/crazy species most!":
        "I'm open to all species except avian":
        "I'm willing to try almost anything if discussed clearly":
        "Will not do characters with antlers or overly complicated anatomy (3 mouths, 4 eyes, etc.)":
        'Critters':
        'Especially less common species':
        'Some scalies':
        'Bugs': # Ambiguous
        "Specialises in mythical creatures/monsters":
        "Most experience in canines":
        "Any sort of animal or fantasy creature, just ask":
        "If I find something would be too complicated to pull off, I may decline.":
        "Basic canines, vulpines, angel dragons. (Will consider if unique)":
        "Reptiles (not including dragons)":
        "Experienced in felines and canines but I'm willing to take on almost anything!":
        "Most anything covered in fur":
        "Prefer making original species":
        'Any really just depends if I can make it will to check into it however give us a shot':
        'Please inquire about fantasy creatures':
        'I especially love to create less common species':
        'Pony': # Does it mean lil horse or MLP?
        'Anything that is possible':
        'I specialize in dragons':
        'Complex hybrids':
        'Up to new species as a challenge':
        'Deer&similar':
        "Rare species":
        'Anything requiring extensive electronics (ex: true-to-species protogens, though we could do a simplified "toony" version)':

    leave_unchanged:
      - 'Anything requiring extensive electronics (ex: true-to-species protogens, though we could do a simplified "toony" version)'
      - I'd prefer not to do any pokemon/digimon, but still ask since it depends on the design
      - Nothing on the hard pass list, but I do not have experience with scalies or other animals without fur. I am willing to try anything!
      - Any species that is furry! (canines, felines, fur dragons, horses, rodents, bats, etc.)
      - Almost everything. Just ask
      - If I find something would be too complicated to pull off, I may decline.
      - skullsuits... # FIXME: How the heck am i supposed to interpret that
      - None specifically that I can think of, if unsure just ask
      - Will not do characters with antlers or overly complicated anatomy (3 mouths, 4 eyes, etc.)
      - I'm willing to take on any species, but enjoy making monsters and creepy/crazy species most!
      - Any and all within my capabilities of foam/fur/minky crafting. Unique or uncommon species are my soft spot.
      - Only things that are completely and literally impossible, like breaking the laws of physics
      - Some birds (unless its on another headbase then I'll do it)
      - Dutch Angel Dragons (Tail, paws and feet paws ONLY)
      - Any sort of animal or fantasy creature, just ask
      - Basic canines, vulpines, angel dragons. (Will consider if unique)
      - Etc.
      - "I greatly prefer uncommon species and will be much more excited to work on such species. I do all, but uncommon is prefered."
      - 'Any animal and most mysticals (dragons*, serials, gryphons)'
      - 'Species with robotic/cybernetic, or otherwise mechanical appearance'

    replacements:
      '"([^"]+)"':                                                  '$1'

      '(((Any and )?All ?|Anything|Any|all) ?(species?|creatures?|kind|really)( (are )?welcome)?)':    'Most species'
      '(Will(ing)? (to )?(try|craft|do) Any(thing| species)?)':                                        'Most species'
      '((I will do just about|We are okay with|Happy to do) any species!?)':                           'Most species'
      '(I''m (willing|open) to (take on any species|consider anything))':                              'Most species'
      '(Everything and anything|Anything!?|any ?!?|all ?!?)':                                          'Most species'

      '(Almost everything\. Just ask|Almost (all|Any)(thing| species?| animals?)?)':                   'Most species'
      '(All species for the most part|Open to most species|Most animals OK|Most species considered)':  'Most species'
      '(Basically anything! Except what''s stated below|Almost any :\)|Most/Any)':                     'Most species'
      '(Pretty much anything|Just ask|Most common species)':                                           'Most species'
      'Any species':                                                                                   'Most species'

      '^(None|Nope|no)$':                                    ''
      '(\s|^)(and|or)':                                      '' # FIXME

      'I can craft any real life animal':                    'Real life animals'

      "AD's|(Ange?le? dragons?)":                            'Angel Dragons'
      'Antelopes?':                                          'Antelopes'
      'Avians?':                                             'Birds'
      'Bats?':                                               'Bats'
      'Bears?':                                              'Bears'
      'Big/small felines':                                   "Big felines\nSmall felines"
      'Big and small cats':                                  "Big cats\nSmall cats"
      'Big (cats|felines)( in general)?':                    "Big cats"
      'Birds?':                                              'Birds'
      'Birds/avians in general':                             'Birds'
      'Bunn(y|ies)':                                         'Rabbits'
      'Caracles|Caracals?':                                  'Caracals'
      'Cats?( in general)?':                                 'Felines'
      'Canines?( in)? ?(\(?general\)?)?':                    'Canines'
      'copyrighted characters?[ !]*':                        'Copyrighted characters'
      '(any )?Closed? species?':                             'Closed species'
      'Deers?':                                              'Deers'
      'Dinosaurs?':                                          'Dinosaurs'
      'Dogs?':                                               'Dogs'
      'Domestic Cats?':                                      'Domestic cats'
      'Dragons?':                                            'Dragons'
      'Dre[ck]{2}ubus(es)?':                                 'Drekkubuses'
      'Dutch Angel Dragons/Angel Dragons':                   "Dutch Angel Dragons\nAngel Dragons"
      'DAD''s|Dutch ange?le? dragons?':                      'Dutch Angel Dragons'
      'Equines?( in general)?':                              'Equines'
      'Etc\.?':                                              'Etc.'
      'Fantasie':                                            'Fantasy creatures'
      'Felines?( in general)?':                              'Felines'
      'Fennecs?( foxes)?':                                   'Fennecs'
      'Ferrets?':                                            'Ferrets'
      'Fish(es)?':                                           'Fishes'
      'Fox(es)?':                                            'Foxes'
      'Gem Raptors?':                                        'Gem raptors'
      'Goats?':                                              'Goats'
      'Griff[io]ns?':                                        'Gryphons'
      'Horses?':                                             'Horses'
      'Hybride?s?':                                          'Hybrids'
      'Hyenas?':                                             'Hyenas'
      'K-9''s':                                              'Canines'
      'Lions?':                                              'Lions'
      'Mammals?( in general)?':                              'Mammals'
      'Mann?okits?':                                         'Manokits'
      'Monkeys?( in general)?':                              'Monkeys'
      'Mouse':                                               'Mice'
      'Open species?':                                       'Open species'
      'Opossums?':                                           'Opossums'
      'Otters?':                                             'Otters'
      'Pandas?':                                             'Giant pandas'
      'Pinnipeds?( in general)?':                            'Pinnipeds'
      'Primagens and protogens':                             "Primagens\nProtogens"
      'Pokemons?':                                           'Pokemons'
      'Primagens?':                                          'Primagens'
      'Protogens?':                                          'Protogens'
      'Protogens/primagens \(on a foam base\)':              "Protogens (on a foam base)\nPrimagens (on a foam base)"
      'Rams?':                                               'Sheeps'
      'Racc?oo?ns?':                                         'Raccoons'
      'Rats?':                                               'Rats'
      'Rare/closed species':                                 "Rare species\nClosed species"
      'Red pandas?':                                         'Red pandas'
      'Reptiles?':                                           'Reptiles'
      'Reptilians?( in general)?':                           'Reptiles'
      'Robots?':                                             'Robots'
      'Rodents?( in general)?':                              'Rodents'
      'Sables':                                              'Sable antelope'
      '(any )?Scalies?( in general)?':                       'Scalies'
      'Ser[gi]als?':                                         'Sergals'
      'Sheeps?':                                             'Sheeps'
      'Skull Animals?':                                      'Skull animals'
      'Small felines?':                                      'Small cats'
      'Snow leopards?':                                      'Snow leopards'
      'Wicker ?beas?ts?':                                    'Wickerbeasts'
      'Wolf':                                                'Wolves'
      'Ungulates?(( in)? \(?general\)?)?':                   'Ungulates'
      'Vulpines?':                                           'Vulpines'
