---
# Not using Ansible Vault, because no.

# contact_email:           ''
# s3_copies_bucket_url:    ''

# app_secret: ''

# google_recaptcha_site_key:        ''
# google_recaptcha_secret:          ''
# google_recaptcha_score_threshold:

# aws_default_region:    ''
# aws_access_key_id:     ''
# aws_secret_access_key: ''
