# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

legacy_index:
  path: /index.html
  controller: &redirect Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: main

legacy_new:
  path: /new.html
  controller: *redirect
  defaults:
    route: new_creators

legacy_events:
  path: /events.html
  controller: *redirect
  defaults:
    route: events

legacy_info:
  path: /info.html
  controller: *redirect
  defaults:
    route: info

legacy_tracking:
  path: /tracking.html
  controller: *redirect
  defaults:
    route: tracking

legacy_maker_ids:
  path: /maker_ids.html
  controller: *redirect
  defaults:
    route: creator_ids

legacy_donate:
  path: /donate.html
  controller: *redirect
  defaults:
    route: donate

legacy_guidelines_1:
  path: /rules.html
  controller: *redirect
  defaults:
    route: guidelines

legacy_guidelines_2:
  path: /rules
  controller: *redirect
  defaults:
    route: guidelines

legacy_should_know:
  path: /should_know.html
  controller: *redirect
  defaults:
    route: should_know

legacy_statistics:
  path: /statistics.html
  controller: *redirect
  defaults:
    route: statistics

legacy_data_updates:
  path: /data_updates.html
  controller: *redirect
  defaults:
    route: iu_form_step_start
